# Generated by Django 3.2.5 on 2021-07-31 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('header_title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filter')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lang')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order_num', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('news_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newsdetail')),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lang'),
        ),
    ]
