# Generated by Django 3.2.5 on 2021-07-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='news_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.newsdetail'),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='core.filter'),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='core.lang'),
        ),
    ]
