# Generated by Django 3.2.5 on 2021-07-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210731_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order_num']},
        ),
    ]
