# Generated by Django 3.2.5 on 2021-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['order_num']},
        ),
        migrations.AddField(
            model_name='filter',
            name='order_num',
            field=models.IntegerField(default=1, verbose_name='Приоритет по фильтрации'),
            preserve_default=False,
        ),
    ]
